
app:
  datasource:
    jdbc-url: jdbc:oracle:thin:@localhost:1521:orclkris
    username: c##scott
    password: PARAMora1
    pool-size: 30
    

logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG